### ISSUE TITLE
Add z_index

### ISSUE THREAD

**Issue by Wuzzy2** [kestral246/vignette#1]
Please add `z_index=-400` to the HUD defintion in `hud_add`.

According to `lua_api.txt`:

> The `z_index` field specifies the order of HUD elements from back to front.
> Lower z-index elements are displayed behind higher z-index elements. Elements
> with same z-index are displayed in an arbitrary order. Default 0.
> Supports negative values. By convention, the following values are recommended:
> 
> *  -400: Graphical effects, such as vignette
> (...)

**Comment by kestral246** [comment]
Done. Thanks for the info.
